### PR TITLE
Continuation passing style

### PR DESCRIPTION
**Pull request by omphalos**
Hello,

I have created a branch where I changed the interp function to use continuation passing style.  

There are many benefits to using continuation passing style for something like this, such as:
- It becomes straightforward to introduce a debugger
- It is possible to instrument running JavaScript
- JavaScript can be run in a custom scheduler
- (and many other things as well)

The downside is that continuation-laden code is not as pretty as code that is continuation-free.  I opted for IcedCoffeeScript as the least-bad way to address this, since it's not a big change from CoffeeScript, and is prettier (in my opinion) than many of the other alternatives out there for handling JavaScript continuations.

Overall, I think the added power that continuation passing style gives the interpreter makes it a valuable addition to this project.

### CODE REVIEW

**Comment by int3** [comment]
Funnily enough, I was thinking of doing the exact same thing so I could implement `yield`, so this is awesome -- thanks! However, right now I see metajs as being more of a demonstration hack than something to be used, so I was thinking of having the CPS interpreter as a separate file. How does that sound?

**Comment by omphalos** [comment]
I'm fine with putting it in another file, but there might be another way to handle it, that I'd like to get your take on.

The drawback with two files is that future changes will potentially have to be made in two places.  I can see the value of keeping interpreter.coffee as it stands as a demonstration hack.  One possibility is to just have another repo or branch for the CPS stuff.  That way changes in either version of the code can be selectively incorporated into the other one.  Changes would still need to be made in two places, but we could leverage git to manage the process of incorporating changes from one version of the code to the other.  I'm not sure if that's the best way to do it, but I just want to throw the idea out there.

On the other hand, keeping everything in one repo and  branch means that the tests will help ensure that most changes are kind of immediately reflected in both versions of the code at once, so there's a benefit to doing it that way too.

What do you think?

**Comment by int3** [comment]
I'd prefer to keep them on the same branch. With the number of differences that already exist between the two interpreters, I don't think git merge would help us that much. Also, (as you mentioned) tests will help us keep two (or more) interpreters to the same standard. Finally, the CPS code will be more discoverable if it's on `master`, which is nice.

**Comment by omphalos** [comment]
Fair enough.  I should have a chance to update this pull request over the next couple days.

**Comment by int3** [comment]
I just did the git wrangling myself, including squashing your commits so the history looks cleaner. Made some minor modifications to your README / commit message, but the code is otherwise intact, and the commits are still under your name. Thanks for the contribution!

**Comment by omphalos** [comment]
Great, thanks!

**Comment by int3** [comment]
@omphalos: Just thought I'd let you know -- I've refactored it to use an error continuation, thus eliminating all the "return if e is not null" checks, plus creating more opportunities for us to pass the "normal" continuation along to the next `interp` function without a extra `defer`. Have a look when you have the time!

**Comment by omphalos** [comment]
Wow, the code is much cleaner this way.  Looks great!

**Pull request closed without merging**
