### PR TITLE
Support injecting a custom scheduler (such as a debugger).

### PR DESCRIPTION
**Pull request by omphalos**
I have added a factory method around interp called createInterpreter.  This function takes a 'scheduler' function, and returns an interpreter that uses the scheduler.  Scheduler is given the ability to determine when the continuations are called.  This scheduler can be something simple like a setTimeout-based scheduler or also something like a JavaScript-based debugger.

### CODE REVIEW

**Comment by int3** [comment]
Sorry, I should have told you earlier, but I'm doing a major refactor of the code right now, including adding a 'scheduler' and a web frontend. Thanks for your contributions so far though, I'll be adding you to the credits.

**Comment by omphalos** [comment]
Mmm, okay.  Well, I started something similar in my local repo, including an HTML demo of a simple step-through debugger (with breakpoints and local eval).  I'm not sure if web-based debugging is part of your planned refactor.  If it isn't, I'd like to contribute something like that once you're done.  I'll hold off posting any pull requests for now.

Also, I found a couple other bugs and will probably just open issues for the time being.  If you'd like help on something in particular, please reach out.

**Comment by int3** [comment]
Yeah, I implemented something like what you described -- I've just pushed it. I don't have breakpoints, though, and I wouldn't object if you wanted to add that in. I'm not exactly good with UI either, so it's kind of ugly; feel free to revamp it and / or add more structure to the view rendering code.

I looked at your approach with the scheduler / stepper, and I think adding it in via monkeypatching and messages is nicer and more decoupled than passing it in as a parameter. The downside is that the recursive calls to `evaluate` (previously `interp`) have to be qualified as `root.evaluate`.

Anyway, I'm pretty much done with it for now, so feel free to run with it if you're still interested. Once that's settled we can do another post to reddit / hackernews :)

**Comment by omphalos** [comment]
I think it's a great demo of the functionality.  Playing around with it, there's a few minor issues in the UI that I encountered:
Switching between demos while autostepping can cause the interpreter to get into a bad state.
I would consider body > div { border-radius: 4px; } to make the border radii more consistent.
Shrinking my browser window seems to destroy the layout (which will be an issue for some mobile users). One way to handle this would be media queries.
I'll have time on Saturday to work on these issues (unless you want to do it sooner youself).  I can also open github issues for these if you'd like me to.
Overall, it looks great!  I'm glad to see something like this in the browser -- I've looked and looked but haven't found anything.  The closest thing is continuum.

**Comment by int3** [comment]
All those changes sound good. Go for it! Github issues aren't necessary unless you want to.

Yeah, this is something I've wanted to see for a while too. It's great to find someone else who agrees :)

**Comment by omphalos** [comment]
Hello,

I just want to give you an update that unfortunately I won't be able to complete these changes by today, but I will be able to complete them soon (I expect Monday).  I understand if you want to go ahead and post the project on reddit & HN rather than wait, as it's a very cool project and I can imagine you're eager to hear people's response (as am I).    

I do want to let you know that http://int3.github.com/metajs isn't working in Firefox for me, which you may consider fixing if you decide not to wait for my changes.  If you do decide to wait, I will fix this as well in my change-set.  I'm sorry that I'm not able to complete these changes sooner - something has come for me and my free time has vanished from me this weekend in an unexpected way.

**Comment by int3** [comment]
Thanks for the update! Don't worry, I'm not in a hurry to get this posted up. Take your time to finish things. :)

**Pull request closed without merging**
